### ISSUE TITLE
Связь с главным классом

### ISSUE THREAD

**Issue by aw5757** [AliveMen/GF#1]
Так, сейчас сделаю свой php-обработчик, в котором буду ловить и распределять запросы от HTML-странички. **Вопрос: что дальше? Как мне вызывать функции твоего класса?**

**Comment by AliveMen** [comment]
как я понимаю к своему файлу php ты должен написать что то вроде include GF.PHP

**Comment by aw5757** [comment]
И всё? И уже могу писать GF->AddPeople() ? Хмм. Попробуем


2015-04-07 14:41 GMT+03:00 AliveMen <notifications@github.com>:

**Comment by AliveMen** [comment]
Да. Именно так.
