### ISSUE TITLE
Таблица с SpecialityOf

### ISSUE THREAD

**Issue by aw5757** [AliveMen/GF#2]
Создай табличку в базе, чтобы я не передавал тебе в функцию pizza,sushi,bbq,pie,fastfood,chinese
Пусть айдишники будут следующими:
* Пицца - 1
* Суши - 2
* Шашлык (BBQ) - 3
* Пироги - 4
* Фастфуд - 5
* Китайская кухня - 6

**Comment by AliveMen** [comment]
готово
