### ISSUE TITLE
Проверка класса

### ISSUE THREAD

**Issue by AliveMen** [AliveMen/GF#3]
Напишу я класс. Как мне запустить его на исполнение?

**Comment by aw5757** [comment]
Единственное, что могу предположить, что нужно его закачать на сервер. Или
на свой локальный сервер. ХЗ как взаимодействовать между гитхабом и
тестированием

2015-04-07 14:46 GMT+03:00 AliveMen <notifications@github.com>:

**Comment by AliveMen** [comment]
это понятно что на сервер. Как его на сервере то запустить?

**Comment by aw5757** [comment]
Ну как? Тестовая страница с хмтл. Там кнопочки, обозначающие вызов фукнции

По нажатии на кнопочку передаётся post запрос в твой PHP файл

PHP файл ловит его, определяет команду и запускает уже фукнцию в Классе.

Собственно, я это сегодня и делаю... Прямо сейчас )

Щас закачаю файл catcher.php в гитхаб. Там, где TODO, предполагается вызов
твоих функций. Думаю, ты можешь для своих проверок сделать что-то
подобное....

2015-04-07 14:49 GMT+03:00 AliveMen <notifications@github.com>:

**Comment by AliveMen** [comment]
тогда я и буду пробовать использовать твой файл

**Comment by aw5757** [comment]
Загрузил вроде. Глянь

**Comment by AliveMen** [comment]
круто. буду седня тестить. закрывай issue

**Comment by aw5757** [comment]
Добро

**Comment by aw5757** [comment]
Для вывода полученных данных оч. хорошо использовать функцию
```phg
var_dump($responce);
```
