### ISSUE TITLE
Как Увидеть Базу?

### ISSUE THREAD

**Issue by aw5757** [AliveMen/GF#4]
Где-то могу увидеть базу? Мне нужны тестовые данные, какие ты уже сам забил. Для имитации различных запросов. И вообще, пока предлагаю оттестить самое главное:
1. Получение списка ресторанов (разные SpecialytyOf по отдельности и в совокупности
2. Получение одного ресторана с меню.

**Comment by AliveMen** [comment]
Базу смотри на вашем сервере.     resource3_GF         7oeEX7JT
Там нет хранимых процедур так как не найден путь как из заливать. 
Письмо в тех поддержку написано.

**Comment by aw5757** [comment]
А не вариант проверить систему на твоём компе?

2015-04-07 22:17 GMT+03:00 AliveMen <notifications@github.com>:

**Comment by AliveMen** [comment]
Я на нем и тестирую. Седня завтра открою доступ к домашней машине из интернета
